Added \'cli configure update\' command.

diff --git a/cli b/cli
--- a/cli
+++ b/cli
@@ -37,6 +37,7 @@ cli_usage() {
   echo "  configure                Configure development environment"
   echo "  configure hooks          Configure talisman hooks"
   echo "  configure download       Download talisman binaries"
+  echo "  configure update         Update talisman binaries if newer version is available"
   echo "  configure search-repos   Search for git repositories,"
   echo
   printf "Commands:\n"
@@ -81,6 +82,7 @@ cli_configure_usage() {
   printf "Commands:\n"
   echo "  hooks          Configure talisman hooks"
   echo "  download       Download talisman binaries"
+  echo "  update         Update talisman binaries if newer version is available"
   echo "  search-repos   Search for git repositories,"
   echo
 
@@ -152,6 +154,47 @@ cli_configure_download_usage() {
   printf "Usage:\n"
   printf "  cli configure download [OPTIONS]\n"
   printf "  cli configure download --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_flags
+    # :flag.usage
+    echo "  --verbose, -v"
+    printf "    Enable verbose output.\n"
+    echo
+
+    # :flag.usage
+    echo "  --repo-org, -r REPO-ORG"
+    printf "    The repo org to download from\n"
+    printf "    Default: thoughtworks/talisman\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cli_configure_update_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "cli configure update - Update talisman binaries if newer version is available\n"
+    echo
+
+  else
+    printf "cli configure update - Update talisman binaries if newer version is available\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  cli configure update [OPTIONS]\n"
+  printf "  cli configure update --help | -h\n"
   echo
 
   # :command.long_usage
@@ -2648,12 +2691,12 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help --path --verbose -h -p -v")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'config search-repos\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help --path --verbose -h -p -v")" -- "$cur" )'
-  echo $'      ;;'
-  echo $''
   echo $'    \'config hooks\'*\'--hook\')'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "pre-commit pre-push")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'config search-repos\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help --path --verbose -h -p -v")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'configure download\'*)'
@@ -2662,6 +2705,10 @@ send_completions() {
   echo $''
   echo $'    \'configure hooks\'*\'-H\')'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "pre-commit pre-push")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'configure update\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help --repo-org --verbose -h -r -v")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'configure hooks\'*)'
@@ -2676,6 +2723,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help --repo-org --verbose -h -r -v")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'config update\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help --repo-org --verbose -h -r -v")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'config hooks\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help --hook --verbose -H -h -v")" -- "$cur" )'
   echo $'      ;;'
@@ -2685,7 +2736,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'configure\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help -h download hooks search-repos")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help -h download hooks search-repos update")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'run\'*\'-H\')'
@@ -2693,7 +2744,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'config\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help -h download hooks search-repos")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cli_completions_filter "--help -h download hooks search-repos update")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'run\'*)'
@@ -2860,14 +2911,31 @@ cli_configure_download_command() {
 }
 
 # :command.function
+cli_configure_update_command() {
+  # src/configure_update_command.sh
+  #!/usr/bin/env bash
+
+  repo_org="${args["--repo-org"]}"
+  binary_name="talisman_$(__os_name)_$(__arch)"
+
+  assets=$(curl -Ls https://api.github.com/repos/"$repo_org"/releases/latest)
+  latest_version=$(echo "$assets" | grep tag_name | awk '{print $2}' | tr -d '"' | tr -d ',' | tr -d 'v')
+  current_version=$(talisman --version | awk '{print $2}')
+
+  if [[ "$latest_version" != "$current_version" ]]; then
+      $(source_dir)/cli configure download
+  fi
+}
+
+# :command.function
 cli_configure_search_repos_command() {
   # src/configure_search_repos_command.sh
   #!/usr/bin/env bash
   path="${args["--path"]}"
 
-  EXTRA_SEARCH_OPTS=""
-  echo -e "\tSearching ${SEARCH_ROOT} for git repositories"
+  echo -e "\tSearching ${path} for git repositories"
 
+  EXTRA_SEARCH_OPTS=""
   SUDO_PREFIX=""
   if [[ "${SEARCH_ROOT}" == "/" ]]; then
     echo -e "\tPlease enter your password when prompted to enable script to search as root user:"
@@ -3006,6 +3074,13 @@ cli_configure_parse_requirements() {
     shift $#
     ;;
 
+  update )
+    action="update"
+    shift
+    cli_configure_update_parse_requirements "$@"
+    shift $#
+    ;;
+
   search-repos )
     action="search-repos"
     shift
@@ -3135,6 +3210,69 @@ cli_configure_download_parse_requirements() {
 
   # :command.command_filter
   action="configure download"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+    # :flag.case
+    --verbose | -v )
+
+      # :flag.case_no_arg
+      args[--verbose]=1
+      shift
+      ;;
+
+    # :flag.case
+    --repo-org | -r )
+
+      # :flag.case_arg
+      if [[ -n ${2+x} ]]; then
+
+        args[--repo-org]="$2"
+        shift
+        shift
+      else
+        printf "%s\n" "--repo-org requires an argument: --repo-org, -r REPO-ORG" >&2
+        exit 1
+      fi
+      ;;
+
+    -?* )
+      printf "invalid option: %s\n" "$key" >&2
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
+      printf "invalid argument: %s\n" "$key" >&2
+      exit 1
+
+      ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args[--repo-org]:-} ]] || args[--repo-org]="thoughtworks/talisman"
+
+}
+
+# :command.parse_requirements
+cli_configure_update_parse_requirements() {
+  # :command.fixed_flags_filter
+  case "${1:-}" in
+  --help | -h )
+    long_usage=yes
+    cli_configure_update_usage
+    exit
+    ;;
+
+  esac
+
+  # :command.command_filter
+  action="configure update"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -3348,6 +3486,14 @@ run() {
       cli_configure_download_usage
     else
       cli_configure_download_command
+    fi
+
+  elif [[ $action == "configure update" ]]; then
+    if [[ ${args[--help]:-} ]]; then
+      long_usage=yes
+      cli_configure_update_usage
+    else
+      cli_configure_update_command
     fi
 
   elif [[ $action == "configure search-repos" ]]; then
